// notes.js — the workbook's methodology text (rows 20–29), carried verbatim
// from workbook-verbatim.md (FR-22). Rendered into the dashboard's methodology
// panel. Kept as data so it stays a single source of truth.

export const NOTES = [
  {
    title: 'WACC',
    body: 'WACC: (Equity%*opportunity cost of equity + Debt%*cost of debt(1-tax rate)) / (Equity% + Debt%)',
  },
  {
    title: 'IRR (Internal Rate of Return)',
    body: "IRR (Internal Rate of Return): The discount rate at which the net present value (NPV) of a project's cash flows equals zero. It represents the expected annualized rate of return generated by an investment.",
  },
  {
    title: 'CAP & IRR',
    body: 'NOTE: Given a constant CAP rate, the IRR will also remain constant, given any combination of NOI and purchase price.',
  },
  {
    title: 'NPV',
    body: "NOTE: NPV is the difference between the present value of all cash flows over the project's duration, discounted by our WACC.",
  },
  {
    title: 'Positive NPV',
    body: "NOTE: A positive NPV indicates that the project's returns exceed that of our WACC and IRR WILL be greater than WACC, making it a worthwhile investment and you should accept the project.",
  },
  {
    title: 'NPV implies IRR > WACC',
    body: 'NOTE: A positive NPV directly implies that the IRR will be greater than our discount rate (WACC).',
  },
  {
    title: 'NPV = 0 (break-even cost of capital)',
    body: "NOTE: When the NPV of all cash flows equals to 0, it means the project's expected cash flows are just enough to cover the cash flows created by our cost of capital (WACC). This represents the project's break-even cost of capital. Setting NPV to 0 will allow us to evaluate the true rate of return of the project (IRR) versus our cost of capital (WACC). If the resulting IRR exceeds our WACC, it means that our project's profitability exceeds that of our WACC and you should accept the project.",
  },
  {
    title: 'NPV formula',
    body: 'NPV= ∑(t=1 to yr)CFt/(1+r)^t − Initial Investment',
  },
  {
    title: 'The (1+r)^t factor',
    body: '(1+r)^t accounts for the compounding effect of the discount rate over time. This factor is what allows us to convert future values to present values, effectively "bringing" future cash flows to the present.',
  },
  {
    title: 'NPV variables',
    body: 'CFt is the cash flow in year t,     r is the discount rate,     t is the number of years (1 to yr)',
  },
];
